### ISSUE TITLE
Remove C-Style arrays and use std containers instead

### ISSUE THREAD

**Issue by Pheelbert** [Pheelbert/battlenetwork#8]
To avoid possible issues and make it more readable.

![overrun](https://user-images.githubusercontent.com/5648665/39016459-856d894e-43ee-11e8-9186-f7248119543f.PNG)

**Comment by TheMaverickProgrammer** [comment]
Yikes. std::containers are slow! Too much overhead for something as simple as keeping track of the selected chip queue. "C-Style" arrays it is ad-hominem to call them that. C/C++ strength is using pointers to control memory. This code is completely safe to use and efficient. I could add more comments to make it readable however this is elementary.

**Comment by TheMaverickProgrammer** [comment]
Those warnings do not appear on my machine. Try pulling my latest changes.

**Comment by Pheelbert** [comment]
https://github.com/isocpp/CppCoreGuidelines/issues/493

Those are the results of the VS2017 static code analyser, they aren't compilation warnings. The fact that it's faster isn't necessarily true and we'll never need that amount of performance even if it were true! One thing we could add is some performance measures (FPS, time to draw, time to update, etc) and whatnot if we're really afraid. This is the case of premature optimization imo

**Comment by TheMaverickProgrammer** [comment]
They're much slower than you think. I care about speed because I'd like to port it to mobile. Let's make a task to add some debugger tools to the game like FPS draws.

**Comment by Pheelbert** [comment]
It's fine if you decide to keep using them; but I suggest looking into it and providing some kind of evidence for what you're saying. All the links I look at say that they have similar performance if used correctly.

another link to show that it's as good: https://stackoverflow.com/questions/15294129/overhead-to-using-stdvector

**Comment by TheMaverickProgrammer** [comment]
they're only as good as the compiler's optimization. In which most cases standard vectors are the same as dynamic arrays. For mobile this will certainly not be the case. In the chip queuing case I really want a list I can throw away because they point to existing chips. If I went with a vector I'd need to be sure they were pointed away and not invoke the deconstructor. With this list if I wanted I can just make one call to "delete [ ] selectedQueue;" and be done. 

See [this bit](https://stackoverflow.com/a/383518/3624674) about unitialized memory which is exactly what I do with the selected queue.

**Comment by Pheelbert** [comment]
I doubt what you're describing here isn't possible or as fast with containers such as array and vector. Here's another link: https://stackoverflow.com/a/383518 !

**Comment by TheMaverickProgrammer** [comment]
Same link?

**Comment by Pheelbert** [comment]
Well you edited your comment so I didn't see it was the same! Is this queue critical to performance? Can you imagine a scenario where this initialization thing would actually bog up that much resources?

**Comment by TheMaverickProgrammer** [comment]
Proclaiming usage of standard containers because it's "safer" is, to me, another way of saying "I can't do memory management and neither should anyone else". I've already explained why I did it this way. If you'd like to rewrite it go ahead.

This weekend I'm adding some animation features and working on AI state system.

**Comment by Pheelbert** [comment]
Someone could argue the same as you and tell you you should program it all in C or assembler for that matter! Fact is more complicated doesn't mean better. Also, it IS safer, and, a static code analyzer found that there was an issue. All that being said, I don't really care. Just felt like you should hear what I believe is right.

**Comment by TheMaverickProgrammer** [comment]
It's hardly complicated. It's basic memory management. Don't be intimated by the double pointers. Static code analyzer is just reinforcing 'safe practices' not necessarily important if you're an advanced programmer. 

Sure thanks for sharing.
